### ISSUE TITLE
Stops tag/categories being added to drafts/scheduled posts

### ISSUE THREAD

**Issue by philipjohn** [Automattic/lightweight-term-count-update#11]
I'm not sure why yet, but the plugin appears to be causing tags and categories to not be appropriately saved when updating draft posts or scheduled posts.

Steps to reproduce:

1. Start a new post
2. Assign some tags and/or categories
3. Save as a draft

Expected outcome: Post is saved with the selected tags/categories
Actual outcome: Post is saved but there are no tags/categories assigned

**Comment by philipjohn** [comment]
I should add: disabling the plugin resolved the issue for me, but I have yet to test on a vanilla install to be sure it's this plugin and not some interaction with other code.

**Comment by mboynes** [comment]
@philipjohn Can you confirm that the plugin is up-to-date? #8 fixed a bug that sounds identical.

**Comment by philipjohn** [comment]
Bingo! Thanks Matt!

**Comment by mboynes** [comment]
_Whew!_
